/*
 * This Java source file was generated by the Gradle 'init' task.
 */

package io.chebotarev.wgu_inventory;

import javafx.application.Application;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.stage.Stage;

public class Main extends Application {

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        launch(args);
    }

    @Override
    public void start(Stage stage) throws Exception {
        Parent root = FXMLLoader.load(getClass().getResource("views/Main.fxml"));
        Scene scene = new Scene(root,800,400);

        stage.setTitle("Inventory");
        stage.setScene(scene);
        stage.show();
    }
}
